### ISSUE TITLE
Confirm that the minimum information content should be used, not the maximum

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#138]
I noticed that when a single clique has multiple information content values, we use the smallest of them as the information content of the clique:

https://github.com/TranslatorSRI/Babel/blob/fb5c5c6f340bd42eece9c8a165f51a71a6d0952d/src/node.py#L60-L68

I would have expected us to use the largest value, since I think largest=better when it comes to information content, and the most information-rich identifier in the clique should be used to determine how information-rich we think the clique is generally. Is that right, or is there a reason to use the smallest IC value instead?

**Comment by cbizon** [comment]
The thinking basically went like: one of the big use cases is for filtering nodes in a query.  If you go through a node with low information content, then it is likely to have many edges because you can always say something dumb like (metformin)-treats-(MONDO:000001) when they are some-some edges.     So you might want to say "don't go through nodes with information content < X)".

So you kind of want to key on the worst case scenario - if one of the identifiers from one ontology is really broad, then its likely to bring a lot of edges of this type and you would want to filter it out.

That said - if we are seeing huge differences in IC for equivalent nodes, I don't know what to think.  I guess it would be telling you something about how the different ontologies are put together in terms of granularity?
