### ISSUE TITLE
Special case * Use Disorders ?

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#265]
We have one clique for `Alcohol use disorder` (UMLS:C0001956 + a MEDDRA term).  And we have another clique for `Alcohol abuse` which has a bunch of curies.  The preferred is a MONDO, but there is an exact match in MONDO from there to a DOID for `Alcohol use disorder`.

I think we want these two cliques to be merged.  If that's true then I think we would need to have some by-hand mappings that we apply.

Note that this also seems to apply to Opioid Use Disorder (OUD) and Opioid Abuse.  I suspect that there are numerous examples of this pattern.  This'll be important to sort out for HEAL and LitCoin.

**Comment by gaurav** [comment]
## Alcohol use disorder

We have several cliques for this, which appears to exist in a continuum of meaning from:
* [MONDO:0002046](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=MONDO%3A0002046) "alcohol abuse" (biolink:Disease): 11 identifiers, including UMLS:C0085762 "Alcohol abuse", DOID:1574 "alcohol use disorder", MESH:D000437 "Alcoholism", NCIT:C20701 "Alcohol Abuse"
* [MONDO:0007079](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=MONDO%3A0007079) "alcohol dependence" (biolink:Disease): 19 identifiers, including UMLS:C0001973 "Alcoholic Intoxication, Chronic", NCIT:C93040 "Alcohol Dependence", HP:0030955 "Addictive alcohol use"
  * Also includes UMLS:C3887915 "AERODIGESTIVE TRACT CANCER, SQUAMOUS CELL, ALCOHOL-RELATED, PROTECTION AGAINST", which doesn't seem right.
* [HP:0430037](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=HP%3A0430037) "Abnormal alcohol consumption" (biolink:PhenotypicFeature): single ID clique
  * [HP:5200329](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=HP%3A5200329) "Problematic alcohol consumption" (biolink:PhenotypicFeature): part of the MONDO:0007079 "alcohol dependence" clique
    * [HP:0030955](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=HP%3A0030955) "Addictive alcohol use" (biolink:PhenotypicFeature): single ID clique

## Opioid use disorder
* [MONDO:0001225](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=MONDO%3A0001225) "opioid abuse": 7 identifiers, including UMLS:C0029095 "Opioid abuse"
* [MONDO:0005530](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=MONDO%3A0005530) "opiate dependence": 13 identifiers, including UMLS:C0027412 "Opioid-Related Disorders", UMLS:C0524662 "Opiate Addiction", HP:0033515 "Addictive opioid use"
* [HP:0033515](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=HP%3A0033515) "Addictive opioid use" (biolink:PhenotypicFeature): part of the MONDO:0005530 "opiate dependence" clique 
* [UMLS:C4237237](https://nodenormalization-sri.renci.org/1.4/get_normalized_nodes?curie=UMLS%3AC4237237) "Opioid use disorder, mild": single identifier clique

## Abuse vs dependence

[As of DSM-IV in 2007](https://www.ncbi.nlm.nih.gov/books/NBK44358/), it looks like "alcohol abuse" refers to excessive and problematic use of something without reaching dependence, while "alcohol dependence" refers to withdrawal symptoms, requiring increasing amounts of alcohol, and other related symptoms.

As of DSM-V, "opioid abuse" has been replaced with "opioid use disorder, mild" as per [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8583742/).

## Options

1. Merge all abuse and dependence cliques into a single clique. This will return in a clique with multiple MONDO IDs, but would make it easier to search for the use disorders we need to NER.
2. Maintain the abuse/dependence distinction, but combine other IDs into the right places (e.g. UMLS:C4237237 into "alcohol abuse")
3. Look for relationships in DOID, MeSH, etc. that could provide some clarity and provide better grouping of these diseases.

**Comment by gaurav** [comment]
NameRes Exp (only available behind the RENCI firewall) now returns the MONDO identifiers we want as the first choice as long as you filter to a Biolink type of `biolink:Disease` or `biolink:DiseaseOrPhenotypicFeature`:
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=opioid%20use%20disorder&autocomplete=false&offset=0&limit=10&biolink_type=Disease
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=alcohol%20use%20disorder&autocomplete=false&offset=0&limit=10&biolink_type=Disease

However, without that filter, we still get a whole bunch of OUD/AUD-related publications (especially questionnaires) and procedures from UMLS:
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=alcohol%20use%20disorder&autocomplete=false&offset=0&limit=10
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=opioid%20use%20disorder&autocomplete=false&offset=0&limit=10

@cbizon Is this good enough for LitCoin, or should I try to tweak the way in which we score preferred names vs synonyms to see if I can get it higher up for unfiltered queries? In a pinch I could also add a bunch of these terms to a blocklist so we don't see them at all.

**Comment by cbizon** [comment]
I think for litcoin this is going to be a bit of a problem still - For the EL as currently implemented, we'd really like to see the right answer appearing in the top 10 at least...

**Comment by gaurav** [comment]
Gotcha, I'll see if I can get that to work!

**Comment by gaurav** [comment]
Here's where we're at currently with OUD and AUD. Both are currently at #11 in their respective searches. It's a pretty big score difference at the moment (OUD: 727 -> 329.7, AUD: 626.7 -> 274), which reflects how high our boost is for preferred name matches over synonym matches.

[Opioid Use Disorder](https://name-resolution-sri.renci.org/lookup?string=Opioid%20Use%20Disorder&autocomplete=false&offset=0&limit=11):

1. [UMLS:C5209216 "Opioid Use Disorder Treatment"](https://bioregistry.io/UMLS:C5209216) (biolink:Procedure): Opioid Use Disorder Treatment (score: 727.5171)
2. [UMLS:C4728238 "opioid use disorder information sensitivity"](https://bioregistry.io/UMLS:C4728238) (biolink:Publication): opioid use disorder information sensitivity (score: 684.4232)
3. [UMLS:C5389789 "digital therapeutics for opioid use disorder"](https://bioregistry.io/UMLS:C5389789) (biolink:Procedure): digital therapeutics opioid use disorder, digital therapeutics for opioid use disorder, digital therapeutics for opioid use disorder (treatment)
4. [UMLS:C5541642 "office-based treatment for opioid use disorder"](https://bioregistry.io/UMLS:C5541642) (biolink:Procedure): office-based treatment for opioid use disorder, office-based treatment for opioid use disorder (treatment)
5. [UMLS:C5540817 "all-inclusive payment for opioid use disorder treatment demonstration"](https://bioregistry.io/UMLS:C5540817) (biolink:Activity): all-inclusive payment for opioid use disorder treatment demonstration, all-inclusive payment for opioid use disorder treatment demonstration (treatment)
6. [UMLS:C5202046 "Gene analysis of 16 genes to evaluate risk of opioid-use disorder"](https://bioregistry.io/UMLS:C5202046) (biolink:Procedure): Gene analysis of 16 genes to evaluate risk of opioid-use disorder
7. [UMLS:C5541644 "office-based treatment for opioid use disorder, 70+ minutes in first calendar month"](https://bioregistry.io/UMLS:C5541644) (biolink:Procedure): office-based treatment for opioid use disorder 70+ minutes first calendar month, office-based treatment for opioid use disorder, 70+ minutes in first calendar month, office-based treatment for opioid use disorder, 70+ minutes in first calendar month (treatment)
8. [UMLS:C5541643 "office-based treatment for opioid use disorder, 60+ minutes in subsequent calendar month"](https://bioregistry.io/UMLS:C5541643) (biolink:Procedure): office-based treatment for opioid use disorder, 60+ minutes in subsequent calendar month, office-based treatment for opioid use disorder, 60+ minutes in subsequent calendar month (treatment)
9. [UMLS:C4746537 "Pain management (opioid-use disorder) genotyping panel, 16 common variants (ie, ABCB1, COMT, DAT1, DBH, DOR, DRD1, DRD2, DRD4, GABA, GAL, HTR2A, HTTLPR, MTHFR, MUOR, OPRK1, OPRM1), buccal swab or other germline tissue sample, algorithm reported as positive or negative risk of opioid-use disorder"](https://bioregistry.io/UMLS:C4746537) (biolink:Procedure): PAIN MGT OPIOID USE DO GNOTYP PNL 16 CMN VRNTS, Pain management (opioid-use disorder) genotyping panel, 16 common variants (ie, ABCB1, COMT, DAT1, DBH, DOR, DRD1, DRD2, DRD4, GABA, GAL, HTR2A, HTTLPR, MTHFR, MUOR, OPRK1, OPRM1), buccal swab or other germline tissue sample, algorithm reported as positive or negative risk of opioid-use disorder
10. [UMLS:C5574502 "All inclusive payment for services related to highly coordinated and integrated opioid use disorder (oud) treatment services furnished for the demonstration project"](https://bioregistry.io/UMLS:C5574502) (biolink:Activity): All inclusive payment for services related to highly coordinated and integrated opioid use disorder (oud) treatment services furnished for the demonstration project (score: 346.42648)
11. [MONDO:0005530 "opiate dependence"](http://purl.obolibrary.org/obo/MONDO_0005530) (biolink:Disease): narcotism, Narcotism, addiction opiate, Opioid Addiction, Opiate Addiction, Opioid addiction, opiate addiction, Opioid dependence, opiate dependence, Opiate Dependence, opioid dependence, OPIOID DEPENDENCE, Opioid Addictions, Opioid Dependence, Addiction, Opiate, Addiction, Opioid, Opioid Dependences, Dependence, Opioid, dependence opiates, dependence; opiate, Dependence, Opiate, dependence; opioids, narcotic dependence, Opioid use disorder, dependence narcotic, Opioid Use Disorder, opioids; dependence, opioid use disorder, Disorder, Opioid Use, Addictive opioid use, Opioid Use Disorders, dependence on opiates, Dependence on opiates, Opioid type dependence, opioid type dependence, Opioid-Related Disorder, Opioid related disorders, Opioid-Related Disorders, opioid-related disorders, Opioid-related disorders, Opioid Related Disorders, Opioid type drug dependence, Opioid use disorder, Severe, Opioid use disorder, severe, Opioid dependence (disorder), Opioid use disorder, moderate, opioid dependence (diagnosis), Opioid use disorder, Moderate, Opioid type dependence, unspecified, opioid-related disorders (diagnosis), Opioid type dependence, unspecified use, Opioid use disorder, severe, in early remission, Opioid use disorder, moderate, in early remission, Opioid use disorder, severe, in sustained remission, Opioid use disorder, moderate, in sustained remission, Opioid use disorder, moderate, with opioid induced depressive disorder (score: 329.73413)

[Alcohol use disorder](https://name-resolution-sri.renci.org/lookup?string=Alcohol%20Use%20Disorder&autocomplete=false&offset=0&limit=11):
1. [UMLS:C0679277 "alcohol use disorder classification"](https://bioregistry.io/UMLS:C0679277) (biolink:Publication): alcohol use disorder classification (score: 626.7189)
2. [UMLS:C4529967 "Alcohol Use Disorder (AUD) Treatment"](https://bioregistry.io/UMLS:C4529967) (biolink:Procedure): Alcoholism Treatment, Alcohol Abuse Treatment, Alcohol Use Disorder (AUD) Treatment
3. [UMLS:C4728261 "alcohol use disorder information sensitivity"](https://bioregistry.io/UMLS:C4728261) (biolink:Publication): alcohol use disorder information sensitivity
4. [UMLS:C5389782 "digital therapeutics for alcohol use disorder"](https://bioregistry.io/UMLS:C5389782) (biolink:Procedure): digital therapeutics alcohol use disorder, digital therapeutics for alcohol use disorder, digital therapeutics for alcohol use disorder (treatment)
5. [UMLS:C3870568 "Alcohol use disorder identification test:-:Pt:^Patient:-:AUDIT"](https://bioregistry.io/UMLS:C3870568) (biolink:ClinicalAttribute): Alcohol Use Disorder Identification Test [AUDIT], Alcohol use disorder identification test:-:Pt:^Patient:-:AUDIT, Alcohol use disorder identification test:-:To identify measures at a point in time:^Patient:-:AUDIT
6. [UMLS:C3871151 "Alcohol Use Disorder Identification Test Alcohol Consumption Questions Questionnaire"](https://bioregistry.io/UMLS:C3871151) (biolink:Publication): AUDIT-C, Alcohol use disorder identification test-consumption, Alcohol Use Disorders Identification Test-Consumption, Alcohol Use Disorder Identification Test - Consumption, Alcohol Use Disorder Identification Test Alcohol Consumption Questions Questionnaire
7. [UMLS:C3889431 "Alcohol Use Disorder Identification Test Self-Report Version Questionnaire"](https://bioregistry.io/UMLS:C3889431) (biolink:Publication): AUDIT, Alcohol Use Disorder Identification Test Self-Report Version Questionnaire
8. [UMLS:C3869943 "Alcohol use disorder identification test-consumption:-:Pt:^Patient:-:AUDIT-C"](https://bioregistry.io/UMLS:C3869943) (biolink:ClinicalAttribute): Alcohol Use Disorder Identification Test - Consumption [AUDIT-C], Alcohol use disorder identification test-consumption:-:Pt:^Patient:-:AUDIT-C, Alcohol use disorder identification test-consumption:-:To identify measures at a point in time:^Patient:-:AUDIT-C
9. [UMLS:C3699401 "Alcohol use disorder:Find:Pt:^Patient:Ord"](https://bioregistry.io/UMLS:C3699401) (biolink:ClinicalAttribute): Alcohol use disorder, Alcohol use disorder:Find:Pt:^Patient:Ord, Alcohol use disorder:Finding:To identify measures at a point in time:^Patient:Ordinal
10. [UMLS:C0450985 "Alcohol use disorders identification test"](https://bioregistry.io/UMLS:C0450985) (biolink:Publication): AUDIT, Alcohol Use Disorder Identification Test, Alcohol use disorder identification test, Alcohol use disorders identification test, Alcohol Use Disorders Identification Test, Alcohol Use Disorders Identification Test (AUDIT), AUDIT - Alcohol use disorders identification test, Alcohol use disorders identification test (assessment scale) (score: 331.13156)
11. [MONDO:0007079 "alcohol dependence"](http://purl.obolibrary.org/obo/MONDO_0007079) (biolink:Disease): ALCOHOLISM, Alcoholism, Dipsomania, dipsomania, alcoholism, alcoholisms, ETOH dependence, Alcoholism, NOS, alcohol addiction, Addiction;alcohol, Alcohol Addiction, addiction alcohol, Alcohol addiction, alcoholism chronic, Alcohol dependency, Alcoholism;chronic, Dependence;alcohol, ALCOHOL DEPENDENCE, alcohol; addiction, alcohol dependence, addiction; alcohol, Alcohol Dependence, chronic alcoholism, Chronic alcoholism, Addiction, alcohol, alcohol dependency, Addiction, Alcohol, Alcohol dependence, ALCOHOLISM CHRONIC, Dependence, Alcohol, alcohol; dependence, Alcoholism, chronic, alcohol dependences, addicted to alcohol, dependence; alcohol, disorder alcoholism, Alcohol use disorder, Alcohol Use Disorder, alcoholism disorders, drunkenness; chronic, alcohol use disorder, chronic; drunkenness, Dependency on alcohol, Addictive alcohol use, Alcoholism (disorder), Chronic alcohol abuse, Abuse;alcohol;chronic, Alcohol Use Disorders, Alcohol abuse chronic, ALCOHOL ABUSE CHRONIC, chronic alcohol abuse, alcohol use disorders, Use Disorders, Alcohol, abuse alcohol alcoholism, Persistent alcohol abuse, alcohol abuse alcoholism, Alcohol problem drinking, alcoholism/alcohol abuse, ethyl alcohol; dependence, dependence; ethyl alcohol, Alcohol Use Disorder (AUD), Alcohol dependence syndrome, alcohol dependence syndrome, Alcohol use disorder, Severe, Alcohol use disorder, severe, primary alcohol use disorder, chronic alcohol intoxication, Intoxication;alcohol;chronic, alcoholism chronic disorders, Alcohol dependence (disorder), dependence alcoholism alcohol, Alcoholic dependence syndrome, secondary alcohol use disorder, Chronic Alcoholic Intoxication, alcohol dependence (diagnosis), Alcohol use disorder, Moderate, Alcohol use disorder, moderate, Intoxication, Chronic Alcoholic, Alcoholic Intoxication, Chronic, alcohol use disorder measurement, Alcoholism with alcohol dependence, Persistent alcohol abuse (disorder), alcohol use disorder in the elderly, Persistent alcohol abuse (diagnosis), alcohol dependence, susceptibility to, alcohol dependence, protection against, Personal history of alcohol use disorder, alcohol use with alcohol-induced disorder, primary vs secondary alcohol use disorder, Alcohol abuse, continuous drinking behavior, Alcohol abuse, continuous drinking behaviour, Alcohol use disorder, severe, in early remission, Alcohol use disorder, moderate, in early remission, alcohol use with alcohol induced psychotic disorder, Alcohol use disorder, severe, in sustained remission, alcohol use with alcohol-induced disorder (diagnosis), Alcohol use disorder, moderate, in sustained remission, alcohol use with alcohol-induced disorder psychotic disorder, alcohol use with alcohol induced psychotic disorder (diagnosis), Alcohol use disorder, severe, with alcohol-induced depressive disorder, Alcohol use disorder, moderate, with alcohol-induced depressive disorder, Mental and behavioral disorders due to use of alcohol, dependence syndrome, Mental and behavioural disorders due to use of alcohol, dependence syndrome, aerodigestive tract cancer, squamous cell, alcohol-related, protection against, AERODIGESTIVE TRACT CANCER, SQUAMOUS CELL, ALCOHOL-RELATED, PROTECTION AGAINST, Alcohol use disorder, severe, with alcohol-induced bipolar or related disorder, Alcohol use disorder, severe, with alcohol-induced mild neurocognitive disorder, Alcohol use disorder, moderate, with alcohol-induced bipolar or related disorder, Alcohol use disorder, moderate, with alcohol-induced mild neurocognitive disorder, Alcohol use disorder, severe, with alcohol-induced major neurocognitive disorder, amnestic-confabulatory type, Alcohol use disorder, moderate, with alcohol-induced major neurocognitive disorder, amnestic-confabulatory type, Alcohol use disorder, severe, with alcohol-induced major neurocognitive disorder, nonamnestic-confabulatory type, Alcohol use disorder, moderate, with alcohol-induced major neurocognitive disorder, nonamnestic-confabulatory type (score: 274.00262)

Possible fixes:
1. Rename the OUD and AUD cliques to that phrase so we get preferred name boosting.
2. Remove/block all the UMLS terms above them (or at least enough to get them into the top ten).
3. Add a penalty for matches with very long preferred names.
4. Boost entries with a high clique identifier count.

**Comment by gaurav** [comment]
Adding the exact(ish) index didn't make the database much bigger -- the compressed file is about 10G larger and the Solr index is about 16G larger (from 122.36 GB to 138.39 GB). I set it up on https://name-resolution-sri-dev.apps.renci.org/docs and both OUD and AUD are now in the top 4 and 5 results respectively!
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=alcohol%20use%20disorder&autocomplete=false&offset=0&limit=10
* https://name-resolution-sri-dev.apps.renci.org/lookup?string=opioid%20use%20disorder&autocomplete=false&offset=0&limit=10

I'll need to do more testing to see if this has broken anything -- I have noticed that UMLS entries are doing better on a bunch of searches because they have an exact match with the search query (e.g. UMLS:C1546560 "Specimen Source Codes - Bone" is now the top result for [bone](https://name-resolution-sri-dev.apps.renci.org/lookup?string=bone&autocomplete=false&offset=0&limit=10) because one of its synonyms is "bone").

**Comment by gaurav** [comment]
Apparently we can boost OUD/AUD in the results by 3-4 places just by changing the search query from `(${query})` to `"${query}"`.

**Comment by gaurav** [comment]
- [ ] In the latest result we're also seeing `Opioid use disorders (OUD)` get mapped to UMLS:C4536274 "opioid use with other opioid induced mental and behavioral disorders" (https://name-resolution-sri.renci.org/lookup?string=Opioid%20use%20disorders%20%28OUD%29&autocomplete=false&offset=0&limit=10). So we'll probably need to do some kind of synonym combination to fix this.

**Comment by gaurav** [comment]
This is now fixed in NameRes Dev, which returns:
* For opioid use disorder: MONDO:0005530 "opiate dependence", followed by MONDO:0001225 "opioid abuse" (https://name-resolution-sri.renci.org/lookup?string=opioid%20use%20disorder&autocomplete=false&offset=0&limit=10)
* For "alcohol use disorder": MONDO:0007079 "alcohol dependence", followed by MONDO:0002046 "alcohol abuse" (https://name-resolution-sri.renci.org/lookup?string=alcohol%20use%20disorder&autocomplete=false&offset=0&limit=10)

The updated search query should have helped with this as well, but I'll leave the manual concords in for now. I'm going to close this issue, but please reopen if there's anything I've missed.
