### ISSUE TITLE
Handle missing efo

### ISSUE THREAD

**Issue by cbizon** [TranslatorSRI/Babel#48]
Jim has removed EFO from ubergraph, we will need to get it directly rather than from ubergraph

**Comment by gaurav** [comment]
The question is: does UberGraph still have references TO EFO, and if so, are they comprehensive enough for GWAS work?

**Comment by gaurav** [comment]
MONDO used to do some crosslinking with EFO -- if it has all the links we need, then Nico's proposed solution at https://github.com/TranslatorSRI/Babel/pull/58#issuecomment-1222169230 might work.

**Comment by gaurav** [comment]
Evan has the base data for GWAS catalogues which has the EFO identifiers it uses, so get that and make sure that's in Babel.

**Comment by matentzn** [comment]
Note that the two sources of truth for Mondo EFO mappings:

- The official [MONDO->EFO bindings](https://github.com/EBISPOT/efo/blob/master/src/ontology/components/mondo_efo_mappings.tsv) in EFO itself. These replace EFO ids at release time with MONDO ids in efo.owl
- The [Mondo-EFO cross references](https://github.com/monarch-initiative/mondo/blob/master/src/ontology/mappings/mondo_hasdbxref_efo.sssom.tsv)

The first is more current, but it only reflects the cases where EFO ids in the editors file are literally swapped out for Mondo ids - the EFO ids therefore never surface.

GWAS should already be using the Mondo IDs in this case, since they are canonical in the EFO release. In my experience with GWAS Catalogue, by far the largest chunk of terms are in the EFO "measurement" branch. They hardly link to anything, and are not very valuable in KG work.

**Comment by gaurav** [comment]
Sorry for a lack of updates on this issue, and thanks for the links, Nico!

I currently have 2,219 unique EFO identifiers from Evan that we need to add to Babel. Unfortunately, at least some of those identifiers aren't included in the MONDO-EFO bindings linked to by Nico. My current plan is to rework the [ENZYME handling code](https://github.com/TranslatorSRI/Babel/blob/7536b2593bba01e007af9f5e1c1156460c1415fd/src/datahandlers/ec.py) to dump all the exact matches from EFO IDs in [efo.owl](http://www.ebi.ac.uk/efo/efo.owl) to other code systems into a file. If I understand the reason for dropping EFO from UberGraph, this could cause a problem if we include all the concordances, but as long as we only link each EFO ID to a single identifier already in our system (e.g. MESH or SNOMED) we should be able to pull the EFO ID into Babel without accidentally connecting two unrelated concepts.

**Comment by gaurav** [comment]
Note that we are also interested in EFO terms that don't link to anything, so we want to include that too.

You can tell glommer to not merge if it sees an EFO ID (but it's uncontrolled which one it ends up on).

So:
- [ ] Keep all the EFO IDs (unless there's parts of EFO we don't want -- we used to have measurements and phenotypes, but we left out the PATO-y terms)
- [ ] Pull all of the exact matches from EFO but scrub it before we glom it, and see if there's any principled way to do this

**Comment by gaurav** [comment]
This should have been fixed by PR https://github.com/TranslatorSRI/Babel/pull/120, so I'm going to close it. But please reopen it if NodeNorm's EFO coverage isn't great!
