### ISSUE TITLE
Remove `CHEBI:CHEBI:41423` from PUBCHEM.COMPOUND:2662 results

### ISSUE THREAD

**Issue by gaurav** [TranslatorSRI/Babel#69]
Querying PUBCHEM.COMPOUND:2662 returns CHEBI:CHEBI:41423 as an equivalent ID, which is wrong: https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=PUBCHEM.COMPOUND%3A2662&conflate=true

Note also that `MESH:C105934` is labeled as `[OBSOLETE] celecoxib` -- are we definitely identifying obsolete MESH terms correctly?

**Comment by colleenXu** [comment]
A similar issue: @cbizon noticed that in this screenshot, there is a `CHEBI:CHEBI:` ID but no correct `CHEBI` ID. I noticed that the top synonym seemed to be the UNII ID rather than a human-readable name (vitamin b12)

![Screen Shot 2022-09-23 at 1 48 56 PM](https://user-images.githubusercontent.com/43731687/192057862-1f7c31ed-d2b3-439e-82cf-6ef4e1460112.png)

**Comment by gaurav** [comment]
The `CHEBI:CHEBI:` bug seems to be coming from [`pull_drugcentral` in drugcentral.py](https://github.com/TranslatorSRI/Babel/blob/ac57d35273a5c91282db44b67b694513798435d5/src/datahandlers/drugcentral.py), which creates an `xref` file whose second column is expected to be an identifier only; however, for CHEBI (and only CHEBI) this column includes the `CHEBI:` prefix, and so we double-concatenate it later on. Working on a fix now.
